import { lazy } from 'react'

/**
 * Every page, code-split per module, so the public site never downloads the ERP
 * and a role only pays for the screens it opens.
 *
 * These live in their own module because `routes.jsx` exports a route array
 * rather than a component, and react-refresh requires a file to export either
 * only components or no components at all.
 */
export const HomePage = lazy(() => import('@/pages/website/HomePage').then((m) => ({ default: m.HomePage })))
export const AboutPage = lazy(() => import('@/pages/website/AboutPage').then((m) => ({ default: m.AboutPage })))
export const ServicesPage = lazy(() => import('@/pages/website/ServicesPage').then((m) => ({ default: m.ServicesPage })))
export const CapabilitiesPage = lazy(() => import('@/pages/website/CapabilitiesPage').then((m) => ({ default: m.CapabilitiesPage })))
export const WebsiteClientsPage = lazy(() => import('@/pages/website/ClientsPage').then((m) => ({ default: m.ClientsPage })))
export const SustainabilityPage = lazy(() => import('@/pages/website/SustainabilityPage').then((m) => ({ default: m.SustainabilityPage })))
export const ContactPage = lazy(() => import('@/pages/website/ContactPage').then((m) => ({ default: m.ContactPage })))
export const PortalOrdersPage = lazy(() => import('@/features/portal/pages/PortalOrdersPage').then((m) => ({ default: m.PortalOrdersPage })))
export const PortalOrderPage = lazy(() => import('@/features/portal/pages/PortalOrderPage').then((m) => ({ default: m.PortalOrderPage })))
export const PortalApprovalsPage = lazy(() => import('@/features/portal/pages/PortalApprovalsPage').then((m) => ({ default: m.PortalApprovalsPage })))
export const PortalShipmentsPage = lazy(() => import('@/features/portal/pages/PortalShipmentsPage').then((m) => ({ default: m.PortalShipmentsPage })))
export const ForbiddenPage = lazy(() => import('@/pages/ForbiddenPage').then((m) => ({ default: m.ForbiddenPage })))
export const NotFoundPage = lazy(() => import('@/pages/NotFoundPage').then((m) => ({ default: m.NotFoundPage })))
export const DashboardPage = lazy(() => import('@/features/dashboard/pages/DashboardPage').then((m) => ({ default: m.DashboardPage })))
export const LoginPage = lazy(() => import('@/features/auth/pages/LoginPage').then((m) => ({ default: m.LoginPage })))
export const ForgotPasswordPage = lazy(() => import('@/features/auth/pages/ForgotPasswordPage').then((m) => ({ default: m.ForgotPasswordPage })))
export const UiKitPage = lazy(() => import('@/features/ui-kit/pages/UiKitPage').then((m) => ({ default: m.UiKitPage })))
export const MastersPage = lazy(() => import('@/features/masters/pages/MastersPage').then((m) => ({ default: m.MastersPage })))
export const EmployeesPage = lazy(() => import('@/features/hr/pages/EmployeesPage').then((m) => ({ default: m.EmployeesPage })))
export const DepartmentsPage = lazy(() => import('@/features/hr/pages/DepartmentsPage').then((m) => ({ default: m.DepartmentsPage })))
export const AttendancePage = lazy(() => import('@/features/hr/pages/AttendancePage').then((m) => ({ default: m.AttendancePage })))
export const LeavePage = lazy(() => import('@/features/hr/pages/LeavePage').then((m) => ({ default: m.LeavePage })))
export const PayrollPage = lazy(() => import('@/features/hr/pages/PayrollPage').then((m) => ({ default: m.PayrollPage })))
export const ReportsPage = lazy(() => import('@/features/reports/pages/ReportsPage').then((m) => ({ default: m.ReportsPage })))
export const ShipmentsPage = lazy(() => import('@/features/logistics/pages/ShipmentsPage').then((m) => ({ default: m.ShipmentsPage })))
export const DocumentsPage = lazy(() => import('@/features/logistics/pages/DocumentsPage').then((m) => ({ default: m.DocumentsPage })))
export const TrackingPage = lazy(() => import('@/features/logistics/pages/TrackingPage').then((m) => ({ default: m.TrackingPage })))
export const InvoicesPage = lazy(() => import('@/features/finance/pages/InvoicesPage').then((m) => ({ default: m.InvoicesPage })))
export const BillsPage = lazy(() => import('@/features/finance/pages/BillsPage').then((m) => ({ default: m.BillsPage })))
export const PaymentsPage = lazy(() => import('@/features/finance/pages/PaymentsPage').then((m) => ({ default: m.PaymentsPage })))
export const ExpensesPage = lazy(() => import('@/features/finance/pages/ExpensesPage').then((m) => ({ default: m.ExpensesPage })))
export const OrderPnlPage = lazy(() => import('@/features/finance/pages/OrderPnlPage').then((m) => ({ default: m.OrderPnlPage })))
export const ClientUpdatesPage = lazy(() => import('@/features/clientUpdates/pages/ClientUpdatesPage').then((m) => ({ default: m.ClientUpdatesPage })))
export const VendorsPage = lazy(() => import('@/features/sourcing/pages/VendorsPage').then((m) => ({ default: m.VendorsPage })))
export const RfqPage = lazy(() => import('@/features/sourcing/pages/RfqPage').then((m) => ({ default: m.RfqPage })))
export const QuoteComparisonPage = lazy(() => import('@/features/sourcing/pages/QuoteComparisonPage').then((m) => ({ default: m.QuoteComparisonPage })))
export const MaterialPoPage = lazy(() => import('@/features/sourcing/pages/MaterialPoPage').then((m) => ({ default: m.MaterialPoPage })))
export const GrnPage = lazy(() => import('@/features/sourcing/pages/GrnPage').then((m) => ({ default: m.GrnPage })))
export const AllocationPage = lazy(() => import('@/features/production/pages/AllocationPage').then((m) => ({ default: m.AllocationPage })))
export const StageTrackerPage = lazy(() => import('@/features/production/pages/StageTrackerPage').then((m) => ({ default: m.StageTrackerPage })))
export const DailyOutputPage = lazy(() => import('@/features/production/pages/DailyOutputPage').then((m) => ({ default: m.DailyOutputPage })))
export const GanttPage = lazy(() => import('@/features/production/pages/GanttPage').then((m) => ({ default: m.GanttPage })))
export const InspectionsPage = lazy(() => import('@/features/quality/pages/InspectionsPage').then((m) => ({ default: m.InspectionsPage })))
export const DefectsPage = lazy(() => import('@/features/quality/pages/DefectsPage').then((m) => ({ default: m.DefectsPage })))
export const OrdersPage = lazy(() => import('@/features/orders/pages/OrdersPage').then((m) => ({ default: m.OrdersPage })))
export const OrderNewPage = lazy(() => import('@/features/orders/pages/OrderNewPage').then((m) => ({ default: m.OrderNewPage })))
export const Order360Page = lazy(() => import('@/features/orders/pages/Order360Page').then((m) => ({ default: m.Order360Page })))
export const LeadsPage = lazy(() => import('@/features/crm/pages/LeadsPage').then((m) => ({ default: m.LeadsPage })))
export const ClientsPage = lazy(() => import('@/features/crm/pages/ClientsPage').then((m) => ({ default: m.ClientsPage })))
export const EnquiriesPage = lazy(() => import('@/features/crm/pages/EnquiriesPage').then((m) => ({ default: m.EnquiriesPage })))
export const DesignRequestsPage = lazy(() => import('@/features/design/pages/DesignRequestsPage').then((m) => ({ default: m.DesignRequestsPage })))
export const TechPacksPage = lazy(() => import('@/features/design/pages/TechPacksPage').then((m) => ({ default: m.TechPacksPage })))
export const SamplesPage = lazy(() => import('@/features/design/pages/SamplesPage').then((m) => ({ default: m.SamplesPage })))
export const CostSheetsPage = lazy(() => import('@/features/costing/pages/CostSheetsPage').then((m) => ({ default: m.CostSheetsPage })))
export const QuotationsPage = lazy(() => import('@/features/costing/pages/QuotationsPage').then((m) => ({ default: m.QuotationsPage })))
export const UsersPage = lazy(() => import('@/features/admin/pages/UsersPage').then((m) => ({ default: m.UsersPage })))
export const RolesPage = lazy(() => import('@/features/admin/pages/RolesPage').then((m) => ({ default: m.RolesPage })))
export const AuditLogPage = lazy(() => import('@/features/admin/pages/AuditLogPage').then((m) => ({ default: m.AuditLogPage })))
export const SettingsPage = lazy(() => import('@/features/admin/pages/SettingsPage').then((m) => ({ default: m.SettingsPage })))
